[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
# Fix the module name confusion
namespace_packages = true
explicit_package_bases = true
# Ignore missing imports in certain modules
[[tool.mypy.overrides]]
module = ["dotenv.*"]
ignore_missing_imports = true

[tool.vulture]
exclude = [
    "**/__pycache__/**",
    "**/.venv/**",
    "**/*.pyc",
    ".mypy_cache/**"
]
min_confidence = 80